on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: readinessregistry.azurecr.io
        username: ${{ secrets.acr_readinessregistry_username }}
        password: ${{ secrets.acr_readinessregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/.devcontainer" -f  ".devcontainer/Dockerfile" -t readinessregistry.azurecr.io/readinesscluster1:${{ github.sha }} --label dockerfile-path=.devcontainer/Dockerfile
        docker push readinessregistry.azurecr.io/readinesscluster1:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_readinesscluster1_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep default | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace default`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: default
        container-registry-url: readinessregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_readinessregistry_username }}
        container-registry-password: ${{ secrets.acr_readinessregistry_password }}
        secret-name: readinesscludockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: default
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
          manifests/ingress.yml
        images: |
          readinessregistry.azurecr.io/readinesscluster1:${{ github.sha }}
        imagepullsecrets: |
          readinesscludockerauth
